/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface GeolocationData {
  lat: number;
  lng: number;
  accuracy?: number;
  address?: string;
}

export type DisasterType = 'hurricane' | 'wildfire' | 'flood' | 'earthquake' | 'other';

export interface UserProfile {
  name: string;
  address: string;
  location: GeolocationData;
  disasterType: DisasterType;
  householdSize: number;
  incomeBracket: number; // Annual income in USD
  insuranceStatus: 'insured' | 'uninsured';
  insuranceType?: string; // 'homeowner', 'renter', 'flood', etc.
  occupancyType: 'homeowner' | 'renter';
  hasSpecialNeeds: boolean; // disability or language-access needs
  specialNeedsDetails?: string;
}

export interface AidProgram {
  id: string;
  name: string;
  agency: string;
  disasterType: DisasterType[]; // Supported disasters
  maxAward: number;
  description: string;
  requirementsDescription: string;
  eligibilityCriteria: {
    maxIncome?: number;
    occupancyType?: ('homeowner' | 'renter')[];
    requiresInsurance?: boolean;
    requiresUninsured?: boolean;
    requiresSpecialNeeds?: boolean;
  };
}

export type ApplicationStatus = 
  | 'matched' 
  | 'auto_filled' 
  | 'submitted' 
  | 'under_review' 
  | 'documents_requested' 
  | 'resubmitted' 
  | 'approved' 
  | 'denied';

export interface Application {
  id: string;
  userId: string;
  programId: string;
  programName: string;
  agency: string;
  status: ApplicationStatus;
  amountRequested: number;
  amountApproved?: number;
  lastUpdated: string;
  missingDocuments: string[];
  submittedDocuments: string[];
}

export interface StatusHistoryEntry {
  id: string;
  applicationId: string;
  programName: string;
  previousStatus: ApplicationStatus | 'none';
  newStatus: ApplicationStatus;
  timestamp: string;
  reasoning: string; // Dynamic narrative generated by Gemini or simulated agent
}

export interface ActivityNotification {
  id: string;
  userId: string;
  applicationId?: string;
  type: 'match' | 'auto_fill' | 'submission' | 'status_change' | 'doc_request' | 'approval' | 'denial';
  title: string;
  message: string;
  timestamp: string;
  status: 'unread' | 'read';
  severity: 'info' | 'warning' | 'success' | 'alert';
}

export interface DashboardStats {
  totalMatched: number;
  applicationsSubmitted: number;
  applicationsApproved: number;
  estTotalAidAmount: number; // Running total of approved (or estimated pending) aid
}

// WebSocket Message Types
export type ClientMessageType = 'auth' | 'subscribe';
export type ServerMessageType = 'stats_update' | 'notification' | 'application_update' | 'history_update' | 'full_state';

export interface ClientMessage {
  type: ClientMessageType;
  userId?: string;
  token?: string;
}

export interface ServerMessage {
  type: ServerMessageType;
  payload: any;
}
